2025/09/24 15:58:31 [error] 7#0: *1 lua entry thread aborted: runtime error: /etc/nginx/lua/openfga_check.lua:17: attempt to concatenate field 'proxy_connect_host' (a nil value)
stack traceback:
coroutine 0:
	/etc/nginx/lua/openfga_check.lua: in main chunk, client: 172.25.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:03:05 [error] 7#0: *1 lua entry thread aborted: runtime error: /etc/nginx/lua/openfga_check.lua:17: attempt to concatenate field 'proxy_connect_host' (a nil value)
stack traceback:
coroutine 0:
	/etc/nginx/lua/openfga_check.lua: in main chunk, client: 172.25.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:03:43 [error] 8#0: *2 [lua] openfga_check.lua:21: Could not determine destination host., client: 172.25.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:04:00 [error] 8#0: *1 [lua] openfga_check.lua:21: Could not determine destination host., client: 172.24.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:04:01 [error] 7#0: *2 [lua] openfga_check.lua:21: Could not determine destination host., client: 172.24.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:05:11 [debug] 10#0: *3 [lua] http_connect.lua:253: connect(): poolname: http:host.docker.internal:18080:nil::nil:::
2025/09/24 16:05:11 [warn] 10#0: *3 [lua] openfga_check.lua:51: OpenFGA check for user='alice' to object='domain:httpbin.io'. Response: nil, client: 172.24.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:05:11 [error] 10#0: *3 [lua] openfga_check.lua:55: Error calling OpenFGA: host.docker.internal could not be resolved (3: Host not found), client: 172.24.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:05:11 [info] 10#0: *3 client 172.24.0.1 closed keepalive connection
2025/09/24 16:05:46 [debug] 9#0: *5 [lua] http_connect.lua:253: connect(): poolname: http:openfga:18080:nil::nil:::
2025/09/24 16:05:46 [warn] 9#0: *5 [lua] openfga_check.lua:51: OpenFGA check for user='alice' to object='domain:httpbin.io'. Response: nil, client: 172.24.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:05:46 [error] 9#0: *5 [lua] openfga_check.lua:55: Error calling OpenFGA: openfga could not be resolved (3: Host not found), client: 172.24.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:05:46 [info] 9#0: *5 client 172.24.0.1 closed keepalive connection
2025/09/24 16:05:58 [debug] 7#0: *1 [lua] http_connect.lua:253: connect(): poolname: http:openfga:18080:nil::nil:::
2025/09/24 16:05:58 [warn] 7#0: *1 [lua] openfga_check.lua:51: OpenFGA check for user='alice' to object='domain:httpbin.io'. Response: nil, client: 172.25.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:05:58 [error] 7#0: *1 [lua] openfga_check.lua:55: Error calling OpenFGA: openfga could not be resolved (3: Host not found), client: 172.25.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:05:58 [info] 7#0: *1 client 172.25.0.1 closed keepalive connection
2025/09/24 16:06:05 [debug] 8#0: *3 [lua] http_connect.lua:253: connect(): poolname: http:openfga:8080:nil::nil:::
2025/09/24 16:06:05 [warn] 8#0: *3 [lua] openfga_check.lua:51: OpenFGA check for user='alice' to object='domain:httpbin.io'. Response: nil, client: 172.25.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:06:05 [error] 8#0: *3 [lua] openfga_check.lua:55: Error calling OpenFGA: openfga could not be resolved (3: Host not found), client: 172.25.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:06:05 [info] 8#0: *3 client 172.25.0.1 closed keepalive connection
2025/09/24 16:06:22 [debug] 7#0: *1 [lua] http_connect.lua:253: connect(): poolname: http:openfga:8080:nil::nil:::
2025/09/24 16:06:22 [warn] 7#0: *1 [lua] openfga_check.lua:51: OpenFGA check for user='alice' to object='domain:httpbin.io'. Response: nil, client: 172.25.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:06:22 [error] 7#0: *1 [lua] openfga_check.lua:55: Error calling OpenFGA: openfga could not be resolved (3: Host not found), client: 172.25.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:06:22 [info] 7#0: *1 client 172.25.0.1 closed keepalive connection
2025/09/24 16:08:37 [debug] 8#0: *3 [lua] http_connect.lua:253: connect(): poolname: http:host.docker.internal:18080:nil::nil:::
2025/09/24 16:08:37 [warn] 8#0: *3 [lua] openfga_check.lua:51: OpenFGA check for user='alice' to object='domain:httpbin.io'. Response: nil, client: 172.25.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:08:37 [error] 8#0: *3 [lua] openfga_check.lua:55: Error calling OpenFGA: host.docker.internal could not be resolved (3: Host not found), client: 172.25.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:08:37 [info] 8#0: *3 client 172.25.0.1 closed keepalive connection
2025/09/24 16:15:07 [debug] 8#0: *1 [lua] http_connect.lua:253: connect(): poolname: http:172.26.240.1:18080:nil::nil:::
2025/09/24 16:15:07 [warn] 8#0: *1 [lua] openfga_check.lua:51: OpenFGA check for user='alice' to object='domain:httpbin.io'. Response: {"code":"latest_authorization_model_not_found","message":"No authorization models found for store '01K5Y4R832EZ1E2EK2P4DV2XKC'"}
, client: 172.25.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:15:07 [error] 8#0: *1 [lua] openfga_check.lua:55: Error calling OpenFGA: {"code":"latest_authorization_model_not_found","message":"No authorization models found for store '01K5Y4R832EZ1E2EK2P4DV2XKC'"}
, client: 172.25.0.1, server: , request: "CONNECT httpbin.io:443 HTTP/1.1", host: "httpbin.io:443"
2025/09/24 16:15:07 [info] 8#0: *1 client 172.25.0.1 closed keepalive connection
